{% set name = "sertit" %}
{% set version = "1.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: 4c0359fee23c0f37f20bde038346d5e4d4c7b891a69569f040b91a67a427d5ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dill
    - lxml
    - psutil
    - python >=3.8
    - tqdm
    - cloudpathlib
    - rasterio >=1.3.0
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - geopandas >=0.11.0

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools.
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools.
  doc_url: https://sertit-utils.readthedocs.io/en/latest
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
