{% set name = "sertit" %}
{% set version = "1.3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: 3dd0bee75db67a495fd357fe0eff0aa882e1773a57d4a3aba1ad31394727ece2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - lxml
    - psutil
    - python >=3.7
    - tqdm
    - rasterio >=1.2.2
    - rioxarray >=0.3.1
    - geopandas >=0.9.0

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools
  doc_url: https://sertit.github.io/sertit-utils/
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
