{% set name = "sertit" %}
{% set version = "1.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: 4c2edad976e30c78b6f09af91ab07f4a912887c371024386264d85534ebe17bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - lxml
    - psutil
    - python >=3.7
    - tqdm
    - cloudpathlib
    - rasterio >=1.2.2
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - geopandas >=0.9.0

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools
  doc_url: https://sertit.github.io/sertit-utils/
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
